[package]
name = "github-streak-stats-cli"
version = "1.2.0"
edition = "2021"

[[bin]]
name = "github-streak-stats"
path = "src/main.rs"

[dependencies]
chrono = "0.4.24"
clap = { version = "4.3.0", features = ["derive"] }
github-streak-stats-lib = { version = "0.1.0", path = "../lib" }
