[package]
name = "github-streak-stats-cli"
version = "1.3.0"
edition = "2021"
description = "Show GitHub contribution streak. Export `GITHUB_TOKEN` environment variable with your GitHub personal access token which has `read:user` scope."

[[bin]]
name = "github-streak-stats"
path = "src/main.rs"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.4", features = ["derive"] }
github-streak-stats-lib = { version = "0.2.0", path = "../lib" }
term-table = "1.3.2"
