[package]
name = "github-streak-stats-cli"
version = "1.6.0"
edition = "2021"
description = "Show GitHub contribution streak. Export `GITHUB_TOKEN` environment variable with your GitHub personal access token which has `read:user` scope."

[[bin]]
name = "github-streak-stats"
path = "src/main.rs"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.14", features = ["derive", "env"] }
github-streak-stats-lib = { version = "0.4.0", path = "../lib" }
term-table = "1.4.0"
