[package]
name = "github-streak-stats-cli"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "github-streak-stats"
path = "src/main.rs"

[dependencies]
chrono = "0.4.24"
github-streak-stats-lib = { version = "0.1.0", path = "../lib" }
structopt = "0.3.26"
